# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/ashutoshupreti/Desktop

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/ashutoshupreti/Desktop/GrowCode

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ashutoshupreti/Desktop/GrowCode/CMakeFiles /Users/ashutoshupreti/Desktop/GrowCode//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ashutoshupreti/Desktop/GrowCode/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named growcode

# Build rule for target.
growcode: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 growcode
.PHONY : growcode

# fast build rule for target.
growcode/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/growcode.dir/build.make CMakeFiles/growcode.dir/build
.PHONY : growcode/fast

backend/src/database/Database.o: backend/src/database/Database.cpp.o
.PHONY : backend/src/database/Database.o

# target to build an object file
backend/src/database/Database.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/growcode.dir/build.make CMakeFiles/growcode.dir/backend/src/database/Database.cpp.o
.PHONY : backend/src/database/Database.cpp.o

backend/src/database/Database.i: backend/src/database/Database.cpp.i
.PHONY : backend/src/database/Database.i

# target to preprocess a source file
backend/src/database/Database.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/growcode.dir/build.make CMakeFiles/growcode.dir/backend/src/database/Database.cpp.i
.PHONY : backend/src/database/Database.cpp.i

backend/src/database/Database.s: backend/src/database/Database.cpp.s
.PHONY : backend/src/database/Database.s

# target to generate assembly for a file
backend/src/database/Database.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/growcode.dir/build.make CMakeFiles/growcode.dir/backend/src/database/Database.cpp.s
.PHONY : backend/src/database/Database.cpp.s

backend/src/server/main.o: backend/src/server/main.cpp.o
.PHONY : backend/src/server/main.o

# target to build an object file
backend/src/server/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/growcode.dir/build.make CMakeFiles/growcode.dir/backend/src/server/main.cpp.o
.PHONY : backend/src/server/main.cpp.o

backend/src/server/main.i: backend/src/server/main.cpp.i
.PHONY : backend/src/server/main.i

# target to preprocess a source file
backend/src/server/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/growcode.dir/build.make CMakeFiles/growcode.dir/backend/src/server/main.cpp.i
.PHONY : backend/src/server/main.cpp.i

backend/src/server/main.s: backend/src/server/main.cpp.s
.PHONY : backend/src/server/main.s

# target to generate assembly for a file
backend/src/server/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/growcode.dir/build.make CMakeFiles/growcode.dir/backend/src/server/main.cpp.s
.PHONY : backend/src/server/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... growcode"
	@echo "... backend/src/database/Database.o"
	@echo "... backend/src/database/Database.i"
	@echo "... backend/src/database/Database.s"
	@echo "... backend/src/server/main.o"
	@echo "... backend/src/server/main.i"
	@echo "... backend/src/server/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

